image: ros:melodic-ros-base

cache:
  paths:
    - ccache/

before_script:
  - apt update >/dev/null && apt install -y git >/dev/null
  - git clone https://gitlab.com/VictorLamoine/ros_gitlab_ci.git >/dev/null
  - source ros_gitlab_ci/gitlab-ci.bash >/dev/null

catkin build:
  stage: build
  script:
    - catkin build --summarize --no-status --force-color
  artifacts:
    paths:
      - 'catkin_workspace/build'
      - 'catkin_workspace/devel'
    expire_in: 5min

catkin run_tests:
  stage: test
  script:
    - source devel/setup.bash
    - catkin run_tests --no-status --force-color | sed -En '/^-- run_tests.py/,/^-- run_tests.py/p'
    - catkin_test_results # Check if one of the tests failed!
  needs:
    - job: catkin build
      artifacts: true
